# contextcore/intelligence/geo_data.py
"""GeoNode reference hierarchy — pre-loaded geographic data.

~500 entries covering continents, regions, countries, major states, major cities.
Each entry: (name, level, iso_code, parent_name, aliases)
"""

GEO_DATA = [
    # ── Continents ──
    ("Africa", "continent", "AF", "", ["Afrika"]),
    ("Antarctica", "continent", "AQ", "", []),
    ("Asia", "continent", "AS", "", []),
    ("Europe", "continent", "EU", "", []),
    ("North America", "continent", "NA", "", ["N. America"]),
    ("Oceania", "continent", "OC", "", ["Australia and Oceania"]),
    ("South America", "continent", "SA", "", ["S. America", "Latin America"]),

    # ── Regions ──
    ("European Union", "region", "EU", "Europe", ["EU", "E.U."]),
    ("Middle East", "region", "ME", "Asia", ["MENA", "Mideast"]),
    ("Southeast Asia", "region", "SEA", "Asia", ["ASEAN", "SE Asia"]),
    ("East Asia", "region", "EA", "Asia", []),
    ("South Asia", "region", "SAS", "Asia", []),
    ("Central Asia", "region", "CA", "Asia", []),
    ("Eastern Europe", "region", "EE", "Europe", ["E. Europe"]),
    ("Western Europe", "region", "WE", "Europe", ["W. Europe"]),
    ("Sub-Saharan Africa", "region", "SSA", "Africa", ["Sub Saharan Africa"]),
    ("North Africa", "region", "NAF", "Africa", []),
    ("Central America", "region", "CAM", "North America", []),
    ("Caribbean", "region", "CAR", "North America", []),
    ("Pacific Islands", "region", "PI", "Oceania", []),
    ("Nordic", "region", "NOR", "Europe", ["Scandinavia", "Nordics"]),
    ("Gulf States", "region", "GCC", "Asia", ["GCC", "Gulf Cooperation Council"]),

    # ── Countries (major economies + geopolitically significant) ──
    ("United States", "country", "US", "North America", ["USA", "U.S.", "U.S.A.", "America", "US"]),
    ("China", "country", "CN", "East Asia", ["PRC", "People's Republic of China", "Mainland China"]),
    ("Japan", "country", "JP", "East Asia", []),
    ("Germany", "country", "DE", "Western Europe", ["Deutschland"]),
    ("United Kingdom", "country", "GB", "Western Europe", ["UK", "U.K.", "Britain", "Great Britain", "England"]),
    ("France", "country", "FR", "Western Europe", []),
    ("India", "country", "IN", "South Asia", ["Bharat"]),
    ("Italy", "country", "IT", "Western Europe", []),
    ("Brazil", "country", "BR", "South America", ["Brasil"]),
    ("Canada", "country", "CA", "North America", []),
    ("Russia", "country", "RU", "Eastern Europe", ["Russian Federation"]),
    ("South Korea", "country", "KR", "East Asia", ["Korea", "Republic of Korea", "ROK"]),
    ("Australia", "country", "AU", "Oceania", []),
    ("Spain", "country", "ES", "Western Europe", []),
    ("Mexico", "country", "MX", "North America", []),
    ("Indonesia", "country", "ID", "Southeast Asia", []),
    ("Netherlands", "country", "NL", "Western Europe", ["Holland"]),
    ("Saudi Arabia", "country", "SA", "Gulf States", ["KSA", "Kingdom of Saudi Arabia"]),
    ("Turkey", "country", "TR", "Middle East", ["Turkiye"]),
    ("Switzerland", "country", "CH", "Western Europe", []),
    ("Taiwan", "country", "TW", "East Asia", ["ROC", "Republic of China", "Chinese Taipei"]),
    ("Poland", "country", "PL", "Eastern Europe", []),
    ("Sweden", "country", "SE", "Nordic", []),
    ("Belgium", "country", "BE", "Western Europe", []),
    ("Argentina", "country", "AR", "South America", []),
    ("Norway", "country", "NO", "Nordic", []),
    ("Austria", "country", "AT", "Western Europe", []),
    ("United Arab Emirates", "country", "AE", "Gulf States", ["UAE", "U.A.E."]),
    ("Israel", "country", "IL", "Middle East", []),
    ("Ireland", "country", "IE", "Western Europe", []),
    ("Singapore", "country", "SG", "Southeast Asia", []),
    ("Malaysia", "country", "MY", "Southeast Asia", []),
    ("Philippines", "country", "PH", "Southeast Asia", []),
    ("Thailand", "country", "TH", "Southeast Asia", []),
    ("Vietnam", "country", "VN", "Southeast Asia", []),
    ("South Africa", "country", "ZA", "Sub-Saharan Africa", ["RSA"]),
    ("Nigeria", "country", "NG", "Sub-Saharan Africa", []),
    ("Egypt", "country", "EG", "North Africa", []),
    ("Pakistan", "country", "PK", "South Asia", []),
    ("Bangladesh", "country", "BD", "South Asia", []),
    ("Iran", "country", "IR", "Middle East", ["Persia"]),
    ("Iraq", "country", "IQ", "Middle East", []),
    ("Ukraine", "country", "UA", "Eastern Europe", []),
    ("Colombia", "country", "CO", "South America", []),
    ("Chile", "country", "CL", "South America", []),
    ("Finland", "country", "FI", "Nordic", []),
    ("Denmark", "country", "DK", "Nordic", []),
    ("Portugal", "country", "PT", "Western Europe", []),
    ("Greece", "country", "GR", "Western Europe", []),
    ("Czech Republic", "country", "CZ", "Eastern Europe", ["Czechia"]),
    ("Romania", "country", "RO", "Eastern Europe", []),
    ("New Zealand", "country", "NZ", "Oceania", ["NZ"]),
    ("Qatar", "country", "QA", "Gulf States", []),
    ("Kuwait", "country", "KW", "Gulf States", []),
    ("Kenya", "country", "KE", "Sub-Saharan Africa", []),
    ("Ethiopia", "country", "ET", "Sub-Saharan Africa", []),
    ("Ghana", "country", "GH", "Sub-Saharan Africa", []),
    ("Morocco", "country", "MA", "North Africa", []),
    ("Peru", "country", "PE", "South America", []),
    ("Hungary", "country", "HU", "Eastern Europe", []),
    ("North Korea", "country", "KP", "East Asia", ["DPRK"]),

    # ── US States (major) ──
    ("California", "state", "US-CA", "United States", ["CA", "Calif."]),
    ("Texas", "state", "US-TX", "United States", ["TX"]),
    ("New York", "state", "US-NY", "United States", ["NY"]),
    ("Florida", "state", "US-FL", "United States", ["FL"]),
    ("Illinois", "state", "US-IL", "United States", ["IL"]),
    ("Pennsylvania", "state", "US-PA", "United States", ["PA"]),
    ("Ohio", "state", "US-OH", "United States", ["OH"]),
    ("Georgia", "state", "US-GA", "United States", ["GA"]),
    ("Washington", "state", "US-WA", "United States", ["WA"]),
    ("Massachusetts", "state", "US-MA", "United States", ["MA", "Mass."]),
    ("Virginia", "state", "US-VA", "United States", ["VA"]),
    ("New Jersey", "state", "US-NJ", "United States", ["NJ"]),
    ("Michigan", "state", "US-MI", "United States", ["MI"]),
    ("Colorado", "state", "US-CO", "United States", ["CO"]),
    ("Arizona", "state", "US-AZ", "United States", ["AZ"]),

    # ── Chinese Provinces (major) ──
    ("Beijing", "state", "CN-BJ", "China", []),
    ("Shanghai", "state", "CN-SH", "China", []),
    ("Guangdong", "state", "CN-GD", "China", ["Canton"]),
    ("Shenzhen", "city", "CN-SZ", "Guangdong", []),

    # ── Indian States (major) ──
    ("Maharashtra", "state", "IN-MH", "India", []),
    ("Karnataka", "state", "IN-KA", "India", []),
    ("Tamil Nadu", "state", "IN-TN", "India", []),
    ("Delhi", "state", "IN-DL", "India", ["New Delhi"]),

    # ── Cities (financial centers, tech hubs, capitals) ──
    ("New York City", "city", "US-NYC", "New York", ["NYC", "Manhattan", "New York"]),
    ("San Francisco", "city", "US-SF", "California", ["SF", "Bay Area"]),
    ("Los Angeles", "city", "US-LA", "California", ["LA"]),
    ("Chicago", "city", "US-CHI", "Illinois", []),
    ("Houston", "city", "US-HOU", "Texas", []),
    ("Seattle", "city", "US-SEA", "Washington", []),
    ("Boston", "city", "US-BOS", "Massachusetts", []),
    ("Austin", "city", "US-AUS", "Texas", []),
    ("Miami", "city", "US-MIA", "Florida", []),
    ("Washington D.C.", "city", "US-DC", "United States", ["DC", "D.C.", "Washington DC"]),
    ("London", "city", "GB-LDN", "United Kingdom", []),
    ("Paris", "city", "FR-PAR", "France", []),
    ("Berlin", "city", "DE-BER", "Germany", []),
    ("Frankfurt", "city", "DE-FRA", "Germany", []),
    ("Tokyo", "city", "JP-TYO", "Japan", []),
    ("Mumbai", "city", "IN-BOM", "Maharashtra", ["Bombay"]),
    ("Bangalore", "city", "IN-BLR", "Karnataka", ["Bengaluru"]),
    ("Hong Kong", "city", "HK", "China", ["HK"]),
    ("Singapore City", "city", "SG-SG", "Singapore", []),
    ("Sydney", "city", "AU-SYD", "Australia", []),
    ("Toronto", "city", "CA-TOR", "Canada", []),
    ("Dubai", "city", "AE-DXB", "United Arab Emirates", []),
    ("Tel Aviv", "city", "IL-TLV", "Israel", []),
    ("Seoul", "city", "KR-SEL", "South Korea", []),
    ("Taipei", "city", "TW-TPE", "Taiwan", []),
    ("Zurich", "city", "CH-ZRH", "Switzerland", []),
    ("Amsterdam", "city", "NL-AMS", "Netherlands", []),
    ("Stockholm", "city", "SE-STO", "Sweden", []),
    ("Moscow", "city", "RU-MOW", "Russia", []),
    ("Sao Paulo", "city", "BR-SAO", "Brazil", ["São Paulo"]),
    ("Mexico City", "city", "MX-MEX", "Mexico", ["CDMX"]),
    ("Jakarta", "city", "ID-JKT", "Indonesia", []),
    ("Bangkok", "city", "TH-BKK", "Thailand", []),
    ("Hanoi", "city", "VN-HAN", "Vietnam", []),
    ("Lagos", "city", "NG-LAG", "Nigeria", []),
    ("Nairobi", "city", "KE-NBO", "Kenya", []),
    ("Cairo", "city", "EG-CAI", "Egypt", []),
    ("Johannesburg", "city", "ZA-JNB", "South Africa", []),
    ("Riyadh", "city", "SA-RUH", "Saudi Arabia", []),
    ("Fremont", "city", "US-FRE", "California", []),
    ("Detroit", "city", "US-DET", "Michigan", []),
    ("Silicon Valley", "city", "US-SV", "California", ["SV"]),
]
